---
##
# Install the Gitolite Git repository access manager
#
- name: Gitolite | Copy root key to /tmp
  copy: src=/root/.ssh/id_rsa.pub dest=/tmp/root.pub owner=root group=root mode=644

- name: Gitolite | Create bin directory for the git user
  file: path={{ git_dir }}/bin state=directory owner=git group=git

- name: Gitolite | Clone Gitolite repository
  git: repo=https://github.com/sitaramc/gitolite.git dest={{ git_dir }}/gitolite version=v3.6 depth=1
  sudo_user: git
  sudo: yes

- name: Gitolite | Install gitolite
  command: "{{ git_dir }}/gitolite/install -ln {{ git_dir }}/bin creates={{ git_dir }}/bin/gitolite"
  sudo_user: git
  sudo: yes

- name: Gitolite | Setup gitolite with root's key
  command: "{{ git_dir }}/bin/gitolite setup -pk /tmp/root.pub"
  sudo_user: git
  sudo: yes

- name: Gitolite | Clone the gitolite-admin repo to root
  git: repo=git@localhost:gitolite-admin dest=/root/gitolite-admin

##
#
# Configure the Gitolite Git repository access manager
#

- name: Gitolite | Add the common post receive hook
  copy: src=files/var-git-.gitolite-hooks-common-post-receive dest={{ git_dir }}/.gitolite/hooks/common/post-receive owner=git group=git mode=744

- name: Gitolite | Add the gitolite conf
  copy: src=files/gitolite-admin-conf-gitolite.conf dest=/root/gitolite-admin/conf/gitolite.conf

- name: Gitolite | Create the repository conf directory
  file: path=/root/gitolite-admin/conf/repositories state=directory

- name: Gitolite | Add the repository conf directory.
  template: src=templates/gitolite-admin-conf-repositories-project.conf.j2 dest=/root/gitolite-admin/conf/repositories/{{ project_name }}.conf

- name: Gitolite | Create the user conf directory.
  file: path=/root/gitolite-admin/conf/users state=directory

- name: Gitolite | Add the git user public key for read only access to pull repos.
  copy: src={{ git_dir }}/.ssh/id_rsa.pub dest=/root/gitolite-admin/keydir/git.pub

- name: Gitolite | Add the project_name user conf
  template: src=templates/gitolite-admin-conf-users-project.conf.j2 dest=/root/gitolite-admin/conf/users/{{ project_name }}.conf

- name: Gitolite | Add the project_name user public key
  copy: src=/home/{{ project_name }}/.ssh/id_rsa.pub dest=/root/gitolite-admin/keydir/{{ project_name }}.pub

- name: Gitolite | Add all files
  shell: git add . chdir=/root/gitolite-admin

- name: Gitolite | Check for modified files before attempting to commit.
  shell: git diff-index --quiet HEAD -- chdir=/root/gitolite-admin
  register: gitolite_modified
  ignore_errors: yes

- name: Gitolite | Commit all changes
  shell: git commit -m "Add {{ project_name }} repo and user via Ansible." chdir=/root/gitolite-admin
  when: gitolite_modified.rc != 0

# Make the repo and setup the user's access.
- name: Gitolite | Push the changes to create the repo.
  shell: git push chdir=/root/gitolite-admin
  when: gitolite_modified.rc != 0
