# Default settings
---

# General settings (Change these!)
project_name: 'project'
project_domain_dev: 'dev.example.com'
project_domain_test: 'test.example.com'
# Site domain without the www, it will be added.
project_domain_live: 'example.com'

# php.ini
php_memory_limit: '256M' 
php_max_execution_time: '90'
php_post_max_size: '32M'
php_upload_max_filesize: '32M'
php_date_timezone: 'America/Los_Angeles'

# apc.ini
apc_rfc1867: '1'
apc_shm_size: '64M'
apc_shm_segments: '1'
apc_num_files_hint: '0'

# my.cnf
