# Default settings
---

# PROJECT CONFIGURATION OPTIONS

# MySQL root password, defaults to blank
mysql_root_password: ''

# Project name is used extensively for the repo, directory and user name. Use a-z, 0-9, and - only.
project_name: 'project'

# Email address administrative emails should go to.
project_email: 'user@example.com'

# Domain name for the development environment
project_domain_dev: 'dev.example.com'

# Domain name for the test/staging environment
project_domain_test: 'test.example.com'

# Domain name for the live environment. Leave out the www. It will be added.
project_domain_live: 'example.com'

# Password for user project_name_dev on project_name_dev database
project_db_password_dev: 'ChangeThisPassword'

# Password for user project_name_test on project_name_test database
project_db_password_test: 'ChangeThisPassword'

# Password for user project_name_live on project_name_live database
project_db_password_live: 'ChangeThisPassword'

# SERVICE CONFIGURATION OPTIONS

# apache HTTP port. Set 8080 for Varnish and modify /etc/apache2/ports.conf 
apache_http_port: '80'

# php.ini
php_memory_limit: '256M'
php_max_execution_time: '90'
php_post_max_size: '32M'
php_upload_max_filesize: '32M'

# apc.ini
apc_rfc1867: '1'
apc_shm_size: '64M'
apc_shm_segments: '1'
apc_num_files_hint: '0'

# my.cnf
